### PR TITLE
added an ability to specify a function as a container queryParam

### PR DESCRIPTION
**Pull request by max-zelinski**

### CODE REVIEW

**Comment by RickWong** [comment]
Do you have a usage example? Normally computations using queryParams can be performed inside the queries themselves.

**Comment by max-zelinski** [comment]
I use it for a seperation of concerns: 
- prepare params in `queryParams`
- query data with prepared params in `queries`

Simple example:

```
Transmit.createContainer(Component, {
  queryParams: {
    filter: function(externalQueryParams) {
      //externalQueryParams.params.filter is a react-router dynamic path parameter
      return externalQueryParams.params.filter || '';
    }
  },
  queries: {
    payments: function(queryParams) {
      return Store.getDataWithFilter(queryParams.filter);
    }
  }
});
```

My real code is a bit more complicated in queryParams part, but unfortunatly I can't share it as is.

**Comment by max-zelinski** [comment]
I also have a case with multiple `queryParams`, some of them must be computed, because they are externally sourced, some of them are static:

```
queryParams: {
    filter: function(externalQueryParams) {
      return externalQueryParams.params.filter || '';
    },
    order: {
      by: undefined,
      direction: undefined
    },
    currentPage: 1,
    perPage: Config.queries.perPage
  }
```

I want to keep them in one place for readability purposes, without spreading them between `queryParams` and `queries`, and to be able to reuse same computed `queryParams` in multiple `queries`.

**Comment by max-zelinski** [comment]
so what are your thoughts on this PR?

**Comment by RickWong** [comment]
It's confusing to have both `queryParams` and "queryLambdas". The latter makes it less predictable what will happen when the parent re-renders or the moment you manually call `setQueryParams`; you'll be asking, does or doesn't the lambda run? Way more predictable if queryParams are just values. 

If you need to apply computations, do it in the queries. To reuse any of those computations, extract them into a separate lib. If you're caching the computations, I wonder if it's the right place for computing. There isn't a real advantage of computations being defined as lambdas in the Transmit definition. At least I don't know of any right now, and I'm not really convinced by `externalQueryParams.params.filter || ''`.

**Comment by RickWong** [comment]
Really appreciate the effort, but the feature is confusing and the supposed benefits still unclear.

**Pull request closed without merging**
