### PR TITLE
Add option not to trigger queries when queryParams equals

### PR DESCRIPTION
**Pull request by alcedoatthis**

### CODE REVIEW

**Comment by ericfong** [comment]
Then, should have "forceQuery" method?

**Comment by alcedoatthis** [comment]
Default functionality was not changed, when You setQueryParams without explicit specification (options.checkEquals = true), queries are triggered. Statics getQuery and getAllQueries are not affected. Hope I did understood the question :-)

**Comment by ericfong** [comment]
Sorry, didn't read the code. I thought that is default action

**Comment by RickWong** [comment]
Sorry, been really busy lately. Thanks for creating this PR. I'll find time to review it soon.

**Comment by RickWong** [comment]
After long consideration, I'm going to add a `shouldComponentUpdate` passthrough option to Transmit so this `shallowEquals` solution can be implemented in userland, outside of Transmit.

Thanks for the PR and discussion!

**Pull request closed without merging**
