### PR TITLE
removed unnecessary reset of onQuery when passing props to a wrapped Component

### PR DESCRIPTION
**Pull request by max-zelinski**
see RickWong/react-transmit#13

### CODE REVIEW

**Comment by RickWong** [comment]
Hi Max, thanks for the PR. Do you have a use-case for passing `onQuery` to the wrapped component?

**Comment by max-zelinski** [comment]
I'm trying to implement [HoC](https://github.com/max-zelinski/spa-prototype/blob/promises-react-transmit/react-reflux-router/js/components/queryContainer.jsx#L32) over react-transmit. [Here](https://github.com/max-zelinski/spa-prototype/blob/promises-react-transmit/react-reflux-router/js/sections/payments.jsx#L61) is how I use it.

I'm actually trying to set an `emptyView` in the component itself. I know you have a [different](https://github.com/RickWong/react-transmit/issues/13#issuecomment-98373304) opinion, but in my case I can have different `emptyView` for each component, and setting it in the parent controller, for example in case if parent controller is a react-router `RouteHandler`, is not very easy/handy.

**Comment by RickWong** [comment]
Your HoC looks solid. However I still cannot find the line where `onQuery` is necessary, and is used in the wrapped component. Can you link to the line of the wrapped component that uses it?

Also I'm sorry for the late response.

**Comment by max-zelinski** [comment]
Sorry about that. 

It seems I had a transmit component wrapping another transmit component. So I had and issue with `onQuery` not being passed from a wrapper component to a wrapped component.

I don't have this case anymore, closing this PR.

**Pull request closed without merging**
