### PR TITLE
test if queryParams after response match current

### PR DESCRIPTION
**Pull request by alcedoatthis**

### CODE REVIEW

**Comment by alcedoatthis** [comment]
I have user-controlled slider which sets queryParams for sibling component and want to be able to check, if queryParams after response still match current. Because of complicated relationship between components i haven't found clear solution on higher level for this. Do You think this could be way to go?

**Comment by RickWong** [comment]
@alcedoatthis :

> i haven't found clear solution on higher level for this.

Can't the parent, of the slider and sibling-Transmit, not hold the slider-state? Then the slider itself can become stateless (i.e. take slider-state as prop input + output via callback) and the parent can pass the same slider-state to the Transmit-container.

I want to avoid any re-implementation of Reacts "shouldComponentUpdate" functionality, if it can be solved simply with a parent React component.

**Comment by XeeD** [comment]
The problem here is, that if you fire a couple of `setQueryParams` on a component and the Promise takes some time to resolve then you can end up with component having props that very for different queryParams that are the current. They might be resolved in different order than the one in which they were sent.

Transmit does not perform a check if the queryParams for which the Promise was created are the same as the current queryParams.

**Comment by XeeD** [comment]
We are setting the queryParams in `componentWillReceiveProps` because the state is not held by the component, it is held by its parent.

**Pull request closed without merging**
